<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => 'mkt_',
	'db_port' => '3306',
	'db_name' => 'mkt',
	'db_user' => 'israel',
	'db_password' => 'senha@123',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'Israel Silva',
	'mailer_from_email' => 'israelsilva1310@gmail.com',
	'mailer_transport' => 'mautic.transport.sendgrid_api',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => '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',
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => 'e7f80ed822f422b3ed7990e00967fcd1ace46b30a3f27e4b63b919e9ffe75b4c',
	'site_url' => 'http://israelcasilva.com.br/mkt/index.php',
);
